#! /bin/bash
apt install docker-compose -y >> /tmp/script.log
apt install git -y >> /tmp/script.log
git clone https://github.com/jcheca/cecoda.git /root/curso >> /tmp/script.log
cat <<EOF >/etc/docker/daemon.json
{
   "log-driver": "json-file",
   "log-opts": {
     "max-size": "10m"
   }
}
EOF

